version: "3.8"

services:
    postgres:
        container_name: pg-container
        image: postgres:14.1
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./pg_data:/var/lib/postgresql/data
            - ./infile:/infile
            - ./db_backup:/tmp